"""Tests for the Alembic migration chain (DBF-AC02).

Drives Alembic entirely through its public Python API
(``alembic.config.Config`` / ``alembic.command``) against a
temporary SQLite file, and reads the result back with SQLAlchemy
(never ``sqlite3`` directly, per DBF-R01). Every test points
``INSPECTFLOW_DATABASE_URL`` at a ``tmp_path`` database and disposes
the shared engine on teardown, so a stale cached engine from an
earlier test (or from this test's own ``get_engine()`` calls)
never leaks into another test or into the real default database
under ``backend/data``.
"""

from pathlib import Path

import pytest
from alembic.config import Config
from alembic.script import ScriptDirectory
from sqlalchemy import create_engine, inspect, text

from alembic import command
from app.db import settings
from app.db.engine import dispose_engine

_BACKEND_DIR = Path(__file__).resolve().parents[2]
_ALEMBIC_INI = _BACKEND_DIR / "alembic.ini"


@pytest.fixture(autouse=True)
def _dispose_shared_engine():
    """Guard against a shared engine leaking in from, or out to,
    another test (see ``test_engine_reuse.py`` for the same
    concern).
    """
    dispose_engine()
    try:
        yield
    finally:
        dispose_engine()


def _alembic_config() -> Config:
    return Config(str(_ALEMBIC_INI))


def test_upgrade_head_creates_a_single_head_and_stamps_it(
    tmp_path, monkeypatch
):
    db_path = tmp_path / "migrations.db"
    monkeypatch.setenv(settings.DATABASE_URL_ENV_VAR, f"sqlite:///{db_path}")
    cfg = _alembic_config()

    command.upgrade(cfg, "head")

    script_dir = ScriptDirectory.from_config(cfg)
    heads = script_dir.get_heads()
    assert len(heads) == 1
    (expected_head,) = heads

    engine = create_engine(f"sqlite:///{db_path}")
    try:
        with engine.connect() as conn:
            stamped = conn.execute(
                text("SELECT version_num FROM alembic_version")
            ).scalar()
    finally:
        engine.dispose()
    assert stamped == expected_head


def test_baseline_upgrade_creates_no_tables_besides_alembic_version(
    tmp_path, monkeypatch
):
    """Upgrades only to the chain's root (the baseline), not to
    ``head``, so this stays true after later migrations add tables.
    """
    db_path = tmp_path / "migrations.db"
    monkeypatch.setenv(settings.DATABASE_URL_ENV_VAR, f"sqlite:///{db_path}")
    cfg = _alembic_config()
    baseline = ScriptDirectory.from_config(cfg).get_base()
    assert baseline is not None

    command.upgrade(cfg, baseline)

    engine = create_engine(f"sqlite:///{db_path}")
    try:
        table_names = inspect(engine).get_table_names()
    finally:
        engine.dispose()
    assert table_names == ["alembic_version"]


def test_check_reports_metadata_in_sync_with_the_migrated_schema(
    tmp_path, monkeypatch
):
    """``alembic check`` compares ``Base.metadata`` (what env.py
    binds ``target_metadata`` to) against the migrated database and
    must find no drift -- proving env.py is wired to the
    application's real metadata rather than an empty stand-in, and
    guarding against a future model being added without a matching
    migration.
    """
    db_path = tmp_path / "migrations.db"
    monkeypatch.setenv(settings.DATABASE_URL_ENV_VAR, f"sqlite:///{db_path}")
    cfg = _alembic_config()
    command.upgrade(cfg, "head")

    command.check(cfg)  # raises AutogenerateDiffsDetected on drift


def test_downgrade_base_removes_the_version_stamp(tmp_path, monkeypatch):
    db_path = tmp_path / "migrations.db"
    monkeypatch.setenv(settings.DATABASE_URL_ENV_VAR, f"sqlite:///{db_path}")
    cfg = _alembic_config()
    command.upgrade(cfg, "head")

    command.downgrade(cfg, "base")

    engine = create_engine(f"sqlite:///{db_path}")
    try:
        # Alembic keeps the bookkeeping table itself (it does not
        # drop it on downgrade), but clears its one row once no
        # revision is applied.
        with engine.connect() as conn:
            row_count = conn.execute(
                text("SELECT count(*) FROM alembic_version")
            ).scalar()
    finally:
        engine.dispose()
    assert row_count == 0


def test_upgrade_head_works_from_a_non_backend_working_directory(
    tmp_path, monkeypatch
):
    """env.py must not depend on the process's current working
    directory to import ``app`` or to locate the database: this
    test runs with ``tmp_path`` (not ``backend/``) as cwd, relying
    only on ``alembic.ini``'s own ``%(here)s``-based
    ``prepend_sys_path`` and on passing an absolute ``alembic.ini``
    path to ``Config``.
    """
    db_path = tmp_path / "migrations.db"
    monkeypatch.setenv(settings.DATABASE_URL_ENV_VAR, f"sqlite:///{db_path}")
    monkeypatch.chdir(tmp_path)
    cfg = _alembic_config()

    command.upgrade(cfg, "head")

    expected_head = ScriptDirectory.from_config(cfg).get_current_head()
    engine = create_engine(f"sqlite:///{db_path}")
    try:
        with engine.connect() as conn:
            stamped = conn.execute(
                text("SELECT version_num FROM alembic_version")
            ).scalar()
    finally:
        engine.dispose()
    assert stamped == expected_head
