"""Tests for the Alembic migration chain (DBF-AC02, DBF-AC08).

Drives Alembic entirely through its public Python API
(``alembic.config.Config`` / ``alembic.command``) against the
database ``conftest.py``'s ``db_url`` fixture configures (a
temporary SQLite file by default, or PostgreSQL under
``--db-backend=postgresql``), and reads the result back with
SQLAlchemy (never ``sqlite3``/``psycopg`` directly, per DBF-R01).
That fixture also points ``INSPECTFLOW_DATABASE_URL`` at the same
database and disposes the shared engine before and after each test,
so a stale cached engine from an earlier test (or from this test's
own ``get_engine()`` calls) never leaks into another test or into
the real default database under ``backend/data``.
"""

import logging
from pathlib import Path

import pytest
from alembic.config import Config
from alembic.script import ScriptDirectory
from sqlalchemy import DateTime, create_engine, inspect, text
from sqlalchemy.orm import Session

from alembic import command

_BACKEND_DIR = Path(__file__).resolve().parents[2]
_ALEMBIC_INI = _BACKEND_DIR / "alembic.ini"


def _alembic_config() -> Config:
    return Config(str(_ALEMBIC_INI))


def _stamped_version(db_url: str) -> str | None:
    engine = create_engine(db_url)
    try:
        with engine.connect() as conn:
            return conn.execute(
                text("SELECT version_num FROM alembic_version")
            ).scalar()
    finally:
        engine.dispose()


def test_upgrade_head_creates_a_single_head_and_stamps_it(db_url):
    cfg = _alembic_config()

    command.upgrade(cfg, "head")

    script_dir = ScriptDirectory.from_config(cfg)
    heads = script_dir.get_heads()
    assert len(heads) == 1
    (expected_head,) = heads

    assert _stamped_version(db_url) == expected_head


def test_baseline_upgrade_creates_no_tables_besides_alembic_version(
    db_url,
):
    """Upgrades only to the chain's root (the baseline), not to
    ``head``, so this stays true after later migrations add tables.
    """
    cfg = _alembic_config()
    baseline = ScriptDirectory.from_config(cfg).get_base()
    assert baseline is not None

    command.upgrade(cfg, baseline)

    engine = create_engine(db_url)
    try:
        table_names = inspect(engine).get_table_names()
    finally:
        engine.dispose()
    assert table_names == ["alembic_version"]


def test_check_reports_metadata_in_sync_with_the_migrated_schema(db_url):
    """``alembic check`` compares ``Base.metadata`` (what env.py
    binds ``target_metadata`` to) against the migrated database and
    must find no drift -- proving env.py is wired to the
    application's real metadata rather than an empty stand-in, and
    guarding against a future model being added without a matching
    migration.
    """
    cfg = _alembic_config()
    command.upgrade(cfg, "head")

    command.check(cfg)  # raises AutogenerateDiffsDetected on drift


def test_downgrade_base_removes_the_version_stamp(db_url):
    cfg = _alembic_config()
    command.upgrade(cfg, "head")

    command.downgrade(cfg, "base")

    # Alembic keeps the bookkeeping table itself (it does not drop
    # it on downgrade), but clears its one row once no revision is
    # applied.
    assert _stamped_version(db_url) is None


def test_downgrade_base_then_upgrade_head_round_trip(db_url):
    """Downgrading to ``base`` and upgrading back to ``head`` from
    there succeeds -- proving the chain survives a downgrade/upgrade
    round trip, not only a single upgrade against a database that
    has never been touched before (DBF-AC08).
    """
    cfg = _alembic_config()
    command.upgrade(cfg, "head")
    command.downgrade(cfg, "base")
    assert _stamped_version(db_url) is None

    command.upgrade(cfg, "head")

    expected_head = ScriptDirectory.from_config(cfg).get_current_head()
    assert _stamped_version(db_url) == expected_head


def test_task_dispatch_time_migration_backfills_only_dispatched_tasks(db_url):
    from datetime import UTC, datetime
    from uuid import UUID, uuid4

    from app.models import InspectionPlan, Project
    from tests.db.conftest import create_root_user_with_company

    cfg = _alembic_config()
    command.upgrade(cfg, "6d2e4f8a91b0")
    engine = create_engine(db_url)
    pending_created = datetime(2026, 10, 1, tzinfo=UTC)
    draft_created = datetime(2026, 10, 2, tzinfo=UTC)
    with Session(engine) as session:
        operator = create_root_user_with_company(session, "DISPATCHMIG")
        project = Project(
            project_code="DISPATCHMIG",
            name="Migration project",
            client_name="Migration client",
            site_location="Migration site",
            created_by=operator.id,
            updated_by=operator.id,
        )
        session.add(project)
        session.flush()
        plan = InspectionPlan(
            project_id=project.id,
            name="Migration plan",
            created_by=operator.id,
            updated_by=operator.id,
        )
        session.add(plan)
        session.flush()
        pending_id = uuid4()
        draft_id = uuid4()
        insert = text(
            "INSERT INTO inspection_tasks "
            "(id, plan_id, project_id, status, created_by, updated_by, "
            "created_at, updated_at) VALUES "
            "(:id, :plan_id, :project_id, :status, :created_by, "
            ":updated_by, :created_at, :updated_at)"
        )
        session.execute(
            insert,
            [
                {
                    "id": pending_id.hex,
                    "plan_id": plan.id.hex,
                    "project_id": project.id.hex,
                    "status": "PENDING",
                    "created_by": operator.id.hex,
                    "updated_by": operator.id.hex,
                    "created_at": pending_created,
                    "updated_at": pending_created,
                },
                {
                    "id": draft_id.hex,
                    "plan_id": plan.id.hex,
                    "project_id": project.id.hex,
                    "status": "DRAFT",
                    "created_by": operator.id.hex,
                    "updated_by": operator.id.hex,
                    "created_at": draft_created,
                    "updated_at": draft_created,
                },
            ],
        )
        session.commit()

    command.upgrade(cfg, "head")
    with engine.connect() as connection:
        rows = (
            connection.execute(
                text(
                    "SELECT id, status, created_at, dispatched_at "
                    "FROM inspection_tasks"
                )
            )
            .mappings()
            .all()
        )
    values = {UUID(str(row["id"])).hex: row for row in rows}
    pending_value = values[pending_id.hex]["dispatched_at"]
    pending_time = (
        pending_value
        if isinstance(pending_value, datetime)
        else datetime.fromisoformat(pending_value)
    )
    if pending_time.tzinfo is None:
        pending_time = pending_time.replace(tzinfo=UTC)
    else:
        pending_time = pending_time.astimezone(UTC)
    assert pending_time == pending_created
    assert values[draft_id.hex]["dispatched_at"] is None
    inspector = inspect(engine)
    task_columns = {
        col["name"]: col for col in inspector.get_columns("inspection_tasks")
    }
    assert task_columns["dispatched_at"]["nullable"] is True
    dispatched_type = task_columns["dispatched_at"]["type"]
    assert isinstance(dispatched_type, DateTime)
    if engine.dialect.name == "postgresql":
        assert dispatched_type.timezone is True
    assert inspector.get_foreign_keys("inspection_tasks")
    engine.dispose()


_PRE_EXISTING_LOGGER_NAME = "tests.db.test_migrations.pre_existing_logger"


@pytest.fixture
def upgraded_db_with_pre_existing_logger(db_url) -> logging.Logger:
    """Create a logger *before* migrating (mirrors the application:
    ``app.api.errors``'s module-level logger already exists by the
    time a migration ever runs), then migrate. Runs during fixture
    setup, like ``tests/auth/conftest.py``'s ``migrated_url`` --
    not inside the test body -- so the assertions below see the
    same pytest log-capture setup real callers see.
    """
    logger = logging.getLogger(_PRE_EXISTING_LOGGER_NAME)
    command.upgrade(_alembic_config(), "head")
    return logger


def test_upgrade_head_keeps_a_pre_existing_logger_enabled(
    upgraded_db_with_pre_existing_logger, caplog
):
    """Issue #185: ``fileConfig``'s default ``disable_existing_loggers``
    is ``True``, which -- when a migration runs in the same process
    as code that already created its own logger (the application, or
    an earlier fixture/test) -- disables that logger for the rest of
    the process. ``env.py`` must pass
    ``disable_existing_loggers=False`` so a logger created before
    ``command.upgrade`` runs still emits records afterwards.
    """
    logger = upgraded_db_with_pre_existing_logger

    assert logger.disabled is False
    with caplog.at_level(logging.INFO, logger=_PRE_EXISTING_LOGGER_NAME):
        logger.info("still alive after migration")

    assert any(
        record.name == _PRE_EXISTING_LOGGER_NAME
        and record.getMessage() == "still alive after migration"
        for record in caplog.records
    )


def test_upgrade_head_works_from_a_non_backend_working_directory(
    db_url, tmp_path, monkeypatch
):
    """env.py must not depend on the process's current working
    directory to import ``app`` or to locate the database: this
    test runs with ``tmp_path`` (not ``backend/``) as cwd, relying
    only on ``alembic.ini``'s own ``%(here)s``-based
    ``prepend_sys_path`` and on passing an absolute ``alembic.ini``
    path to ``Config``.
    """
    monkeypatch.chdir(tmp_path)
    cfg = _alembic_config()

    command.upgrade(cfg, "head")

    expected_head = ScriptDirectory.from_config(cfg).get_current_head()
    assert _stamped_version(db_url) == expected_head
