"""Tests for the Alembic migration chain (DBF-AC02, DBF-AC08).

Drives Alembic entirely through its public Python API
(``alembic.config.Config`` / ``alembic.command``) against the
database ``conftest.py``'s ``db_url`` fixture configures (a
temporary SQLite file by default, or PostgreSQL under
``--db-backend=postgresql``), and reads the result back with
SQLAlchemy (never ``sqlite3``/``psycopg`` directly, per DBF-R01).
That fixture also points ``INSPECTFLOW_DATABASE_URL`` at the same
database and disposes the shared engine before and after each test,
so a stale cached engine from an earlier test (or from this test's
own ``get_engine()`` calls) never leaks into another test or into
the real default database under ``backend/data``.
"""

import logging
from pathlib import Path

import pytest
from alembic.config import Config
from alembic.script import ScriptDirectory
from sqlalchemy import DateTime, create_engine, insert, inspect, text
from sqlalchemy.orm import Session

from alembic import command

_BACKEND_DIR = Path(__file__).resolve().parents[2]
_ALEMBIC_INI = _BACKEND_DIR / "alembic.ini"


def _alembic_config() -> Config:
    return Config(str(_ALEMBIC_INI))


def _stamped_version(db_url: str) -> str | None:
    engine = create_engine(db_url)
    try:
        with engine.connect() as conn:
            return conn.execute(
                text("SELECT version_num FROM alembic_version")
            ).scalar()
    finally:
        engine.dispose()


def test_upgrade_head_creates_a_single_head_and_stamps_it(db_url):
    cfg = _alembic_config()

    command.upgrade(cfg, "head")

    script_dir = ScriptDirectory.from_config(cfg)
    heads = script_dir.get_heads()
    assert len(heads) == 1
    (expected_head,) = heads

    assert _stamped_version(db_url) == expected_head


def test_baseline_upgrade_creates_no_tables_besides_alembic_version(
    db_url,
):
    """Upgrades only to the chain's root (the baseline), not to
    ``head``, so this stays true after later migrations add tables.
    """
    cfg = _alembic_config()
    baseline = ScriptDirectory.from_config(cfg).get_base()
    assert baseline is not None

    command.upgrade(cfg, baseline)

    engine = create_engine(db_url)
    try:
        table_names = inspect(engine).get_table_names()
    finally:
        engine.dispose()
    assert table_names == ["alembic_version"]


def test_check_reports_metadata_in_sync_with_the_migrated_schema(db_url):
    """``alembic check`` compares ``Base.metadata`` (what env.py
    binds ``target_metadata`` to) against the migrated database and
    must find no drift -- proving env.py is wired to the
    application's real metadata rather than an empty stand-in, and
    guarding against a future model being added without a matching
    migration.
    """
    cfg = _alembic_config()
    command.upgrade(cfg, "head")

    command.check(cfg)  # raises AutogenerateDiffsDetected on drift


def test_downgrade_base_removes_the_version_stamp(db_url):
    cfg = _alembic_config()
    command.upgrade(cfg, "head")

    command.downgrade(cfg, "base")

    # Alembic keeps the bookkeeping table itself (it does not drop
    # it on downgrade), but clears its one row once no revision is
    # applied.
    assert _stamped_version(db_url) is None


def test_downgrade_base_then_upgrade_head_round_trip(db_url):
    """Downgrading to ``base`` and upgrading back to ``head`` from
    there succeeds -- proving the chain survives a downgrade/upgrade
    round trip, not only a single upgrade against a database that
    has never been touched before (DBF-AC08).
    """
    cfg = _alembic_config()
    command.upgrade(cfg, "head")
    command.downgrade(cfg, "base")
    assert _stamped_version(db_url) is None

    command.upgrade(cfg, "head")

    expected_head = ScriptDirectory.from_config(cfg).get_current_head()
    assert _stamped_version(db_url) == expected_head


def test_task_dispatch_time_migration_backfills_only_dispatched_tasks(db_url):
    from datetime import UTC, datetime
    from uuid import UUID, uuid4

    from app.models import (
        InspectionPlan,
        InspectionTask,
        Project,
        ProjectInspectionItem,
        ProjectInspectionPoint,
        ProjectMeasurementField,
        ProjectNumericStandard,
        TaskInspectionItem,
        TaskRequirementSnapshot,
        TaskSnapshotMeasurementField,
        TaskSnapshotNumericStandard,
        TaskSnapshotPoint,
        TemplateCategory,
        TemplateInspectionPoint,
        TemplateItem,
        TemplateMeasurementField,
        TemplateNumericStandard,
        TemplateSystem,
    )
    from tests.db.conftest import create_root_user_with_company

    cfg = _alembic_config()
    migration_revision = "62af416d9c01"
    previous_revision = "4f7a1c93d2e6"
    command.upgrade(cfg, previous_revision)
    engine = create_engine(db_url)
    pending_created = datetime(2026, 10, 1, tzinfo=UTC)
    draft_created = datetime(2026, 10, 2, tzinfo=UTC)
    with Session(engine) as session:
        operator = create_root_user_with_company(session, "DISPATCHMIG")
        audit = {
            "created_by": operator.id,
            "updated_by": operator.id,
        }
        category = TemplateCategory(name="Migration category", **audit)
        session.add(category)
        session.flush()
        system = TemplateSystem(
            category_id=category.id,
            name="Migration system",
            **audit,
        )
        session.add(system)
        session.flush()
        template_item = TemplateItem(
            system_id=system.id,
            sequence=1,
            title="Migration template item",
            instruction="Migration template instruction",
            **audit,
        )
        session.add(template_item)
        session.flush()
        template_point = TemplateInspectionPoint(
            template_item_id=template_item.id,
            sequence=1,
            title="Migration template point",
            instruction="Template point instruction",
            **audit,
        )
        session.add(template_point)
        session.flush()
        template_field = TemplateMeasurementField(
            inspection_point_id=template_point.id,
            name="Template measure",
            field_type="number",
            unit="mm",
            sort_order=0,
            **audit,
        )
        session.add(template_field)
        session.flush()
        template_standard = TemplateNumericStandard(
            inspection_point_id=template_point.id,
            value="10",
            condition=">=",
            unit="mm",
            tolerance=None,
            measurement_field_id=template_field.id,
            measurement_field_type="number",
            measurement_field_unit="mm",
            **audit,
        )
        session.add(template_standard)
        session.flush()
        project = Project(
            project_code="DISPATCHMIG",
            name="Migration project",
            client_name="Migration client",
            site_location="Migration site",
            created_by=operator.id,
            updated_by=operator.id,
        )
        session.add(project)
        session.flush()
        project_item = ProjectInspectionItem(
            project_id=project.id,
            sequence=1,
            title="Migration project item",
            instruction="Project item instruction",
            source_template_name="Migration template",
            applied_at=pending_created,
            **audit,
        )
        session.add(project_item)
        session.flush()
        project_point = ProjectInspectionPoint(
            project_inspection_item_id=project_item.id,
            sequence=1,
            title="Migration project point",
            instruction="Project point instruction",
            **audit,
        )
        session.add(project_point)
        session.flush()
        project_field = ProjectMeasurementField(
            inspection_point_id=project_point.id,
            project_inspection_item_id=project_item.id,
            name="Project measure",
            field_type="number",
            unit="mm",
            sort_order=0,
            **audit,
        )
        session.add(project_field)
        session.flush()
        project_standard = ProjectNumericStandard(
            inspection_point_id=project_point.id,
            project_inspection_item_id=project_item.id,
            value="11",
            condition="<=",
            unit="mm",
            tolerance=None,
            measurement_field_id=project_field.id,
            measurement_field_type="number",
            measurement_field_unit="mm",
            **audit,
        )
        session.add(project_standard)
        session.flush()
        plan = InspectionPlan(
            project_id=project.id,
            name="Migration plan",
            **audit,
        )
        session.add(plan)
        session.flush()
        pending_id = uuid4()
        draft_id = uuid4()
        session.execute(
            insert(InspectionTask),
            [
                {
                    "id": pending_id,
                    "plan_id": plan.id,
                    "project_id": project.id,
                    "status": "PENDING",
                    "created_by": operator.id,
                    "updated_by": operator.id,
                    "created_at": pending_created,
                    "updated_at": pending_created,
                },
                {
                    "id": draft_id,
                    "plan_id": plan.id,
                    "project_id": project.id,
                    "status": "DRAFT",
                    "created_by": operator.id,
                    "updated_by": operator.id,
                    "created_at": draft_created,
                    "updated_at": draft_created,
                },
            ],
        )
        for task_id in (pending_id, draft_id):
            association = TaskInspectionItem(
                task_id=task_id,
                project_id=project.id,
                project_inspection_item_id=project_item.id,
                **audit,
            )
            session.add(association)
            session.flush()
            snapshot = TaskRequirementSnapshot(
                task_inspection_item_id=association.id,
                revision=1,
                source_standard_revision=1,
                title="Migration snapshot",
                instruction="Snapshot instruction",
                source_template_name="Migration template",
                **audit,
            )
            session.add(snapshot)
            session.flush()
            snapshot_point = TaskSnapshotPoint(
                snapshot_id=snapshot.id,
                source_point_id=project_point.id,
                sequence=1,
                title="Snapshot point",
                instruction="Snapshot point instruction",
                **audit,
            )
            session.add(snapshot_point)
            session.flush()
            snapshot_field = TaskSnapshotMeasurementField(
                point_id=snapshot_point.id,
                source_field_id=template_field.id,
                name="Snapshot measure",
                field_type="number",
                unit="mm",
                sort_order=0,
                **audit,
            )
            session.add(snapshot_field)
            session.flush()
            session.add(
                TaskSnapshotNumericStandard(
                    point_id=snapshot_point.id,
                    value="12",
                    condition="=",
                    unit="mm",
                    tolerance=None,
                    source_measurement_field_id=snapshot_field.source_field_id,
                    measurement_field_type="number",
                    measurement_field_unit="mm",
                    **audit,
                )
            )
        session.commit()

    tables = (
        "template_categories",
        "template_systems",
        "template_items",
        "template_inspection_points",
        "template_measurement_fields",
        "template_numeric_standards",
        "projects",
        "project_inspection_items",
        "project_inspection_points",
        "project_measurement_fields",
        "project_numeric_standards",
        "inspection_plans",
        "inspection_tasks",
        "task_inspection_items",
        "task_requirement_snapshots",
        "task_snapshot_points",
        "task_snapshot_measurement_fields",
        "task_snapshot_numeric_standards",
    )

    def row_counts() -> dict[str, int]:
        with engine.connect() as connection:
            return {
                table: connection.execute(
                    text(f"SELECT count(*) FROM {table}")
                ).scalar_one()
                for table in tables
            }

    before = row_counts()
    command.upgrade(cfg, migration_revision)
    inspector = inspect(engine)
    assert "dispatched_at" in {
        column["name"] for column in inspector.get_columns("inspection_tasks")
    }
    with engine.connect() as connection:
        values = {
            UUID(str(row["id"])): row
            for row in connection.execute(
                text(
                    "SELECT id, status, created_at, dispatched_at "
                    "FROM inspection_tasks"
                )
            ).mappings()
        }
    assert values[pending_id]["status"] == "PENDING"
    assert (
        values[pending_id]["dispatched_at"] == values[pending_id]["created_at"]
    )
    assert values[draft_id]["status"] == "DRAFT"
    assert values[draft_id]["dispatched_at"] is None
    assert row_counts() == before

    command.downgrade(cfg, previous_revision)
    assert "dispatched_at" not in {
        column["name"]
        for column in inspect(engine).get_columns("inspection_tasks")
    }
    assert row_counts() == before

    command.upgrade(cfg, migration_revision)
    assert row_counts() == before
    with engine.connect() as connection:
        round_trip_values = {
            UUID(str(row["id"])): row
            for row in connection.execute(
                text(
                    "SELECT id, status, created_at, dispatched_at "
                    "FROM inspection_tasks"
                )
            ).mappings()
        }
    assert (
        round_trip_values[pending_id]["dispatched_at"]
        == (round_trip_values[pending_id]["created_at"])
    )
    assert round_trip_values[draft_id]["dispatched_at"] is None
    inspector = inspect(engine)
    dispatched_type = next(
        column["type"]
        for column in inspector.get_columns("inspection_tasks")
        if column["name"] == "dispatched_at"
    )
    assert isinstance(dispatched_type, DateTime)
    if engine.dialect.name == "postgresql":
        assert dispatched_type.timezone is True
    engine.dispose()


_PLANNING_INDEXES = {
    "inspection_tasks": {
        "ix_inspection_tasks_project_created_id": [
            "project_id",
            "created_at",
            "id",
        ],
        "ix_inspection_tasks_plan_created_id": [
            "plan_id",
            "created_at",
            "id",
        ],
        "ix_inspection_tasks_assignee_id": ["assignee_id"],
    },
    "inspection_plans": {
        "ix_inspection_plans_project_created_id": [
            "project_id",
            "created_at",
            "id",
        ],
    },
    "project_inspection_items": {
        "ix_project_inspection_items_project_created_id": [
            "project_id",
            "created_at",
            "id",
        ],
    },
}


def _planning_index_columns(engine) -> dict[str, list[str]]:
    inspector = inspect(engine)
    found = {}
    for table, expected in _PLANNING_INDEXES.items():
        by_name = {
            index["name"]: index["column_names"]
            for index in inspector.get_indexes(table)
        }
        found.update({name: by_name.get(name) for name in expected})
    return found


def test_planning_list_index_migration_adds_and_drops_only_indexes(db_url):
    from datetime import UTC, datetime

    from app.models import (
        InspectionPlan,
        InspectionTask,
        Project,
        ProjectInspectionItem,
    )
    from tests.db.conftest import create_root_user_with_company

    cfg = _alembic_config()
    migration_revision = "b3f9a6d27c41"
    previous_revision = "62af416d9c01"
    expected = {
        name: columns
        for indexes in _PLANNING_INDEXES.values()
        for name, columns in indexes.items()
    }
    command.upgrade(cfg, previous_revision)
    engine = create_engine(db_url)
    assert set(_planning_index_columns(engine).values()) == {None}
    with Session(engine) as session:
        operator = create_root_user_with_company(session, "INDEXMIG")
        audit = {"created_by": operator.id, "updated_by": operator.id}
        project = Project(
            project_code="INDEXMIG",
            name="Index migration project",
            client_name="Demo client",
            site_location="Demo site",
            **audit,
        )
        session.add(project)
        session.flush()
        plan = InspectionPlan(
            project_id=project.id, name="Index migration plan", **audit
        )
        session.add(plan)
        session.flush()
        session.add_all(
            [
                InspectionTask(
                    plan_id=plan.id,
                    project_id=project.id,
                    assignee_id=operator.id,
                    **audit,
                ),
                ProjectInspectionItem(
                    project_id=project.id,
                    sequence=1,
                    title="Index migration item",
                    instruction="Instruction",
                    source_template_name="Template",
                    applied_at=datetime.now(UTC),
                    **audit,
                ),
            ]
        )
        session.commit()

    tables = (
        "users",
        "projects",
        "inspection_plans",
        "inspection_tasks",
        "project_inspection_items",
    )

    def row_counts() -> dict[str, int]:
        with engine.connect() as connection:
            return {
                table: connection.execute(
                    text(f"SELECT COUNT(*) FROM {table}")
                ).scalar_one()
                for table in tables
            }

    before = row_counts()
    assert before["inspection_tasks"] == 1

    command.upgrade(cfg, migration_revision)
    assert _planning_index_columns(engine) == expected
    assert row_counts() == before

    command.downgrade(cfg, previous_revision)
    assert set(_planning_index_columns(engine).values()) == {None}
    assert row_counts() == before

    command.upgrade(cfg, "head")
    assert _planning_index_columns(engine) == expected
    assert row_counts() == before
    engine.dispose()


def test_evidence_unique_migration_keeps_largest_min_count_per_point(
    db_url,
):
    from datetime import UTC, datetime, timedelta
    from uuid import UUID, uuid4

    from app.models import (
        Project,
        ProjectEvidenceRequirement,
        ProjectInspectionItem,
        ProjectInspectionPoint,
        TemplateCategory,
        TemplateEvidenceRequirement,
        TemplateInspectionPoint,
        TemplateItem,
        TemplateSystem,
    )
    from tests.db.conftest import create_root_user_with_company

    cfg = _alembic_config()
    migration_revision = "d5a2c8e7b194"
    previous_revision = "b3f9a6d27c41"
    indexes = {
        "template_evidence_requirements": "uq_template_evidence_point_type",
        "project_evidence_requirements": "uq_project_evidence_point_type",
    }
    base = datetime(2026, 10, 1, tzinfo=UTC)

    def unique_indexes(engine) -> dict[str, bool]:
        inspector = inspect(engine)
        return {
            table: any(
                index["name"] == name and index["unique"]
                for index in inspector.get_indexes(table)
            )
            for table, name in indexes.items()
        }

    command.upgrade(cfg, previous_revision)
    engine = create_engine(db_url)
    assert unique_indexes(engine) == dict.fromkeys(indexes, False)
    kept: dict[str, UUID] = {}
    dropped: list[UUID] = []
    with Session(engine) as session:
        operator = create_root_user_with_company(session, "EVIDMIG")
        audit = {"created_by": operator.id, "updated_by": operator.id}
        category = TemplateCategory(name="Evidence category", **audit)
        session.add(category)
        session.flush()
        system = TemplateSystem(
            category_id=category.id, name="Evidence system", **audit
        )
        session.add(system)
        session.flush()
        template_item = TemplateItem(
            system_id=system.id,
            sequence=1,
            title="Evidence template",
            instruction="Instruction",
            **audit,
        )
        session.add(template_item)
        project = Project(
            project_code="EVIDMIG",
            name="Evidence project",
            client_name="Demo client",
            site_location="Demo site",
            **audit,
        )
        session.add(project)
        session.flush()
        project_item = ProjectInspectionItem(
            project_id=project.id,
            sequence=1,
            title="Evidence project item",
            instruction="Instruction",
            source_template_name="Template",
            applied_at=base,
            **audit,
        )
        session.add(project_item)
        session.flush()
        for sequence, shape in enumerate(
            ("largest", "tie", "single"), start=1
        ):
            template_point = TemplateInspectionPoint(
                template_item_id=template_item.id,
                sequence=sequence,
                title=f"Template point {shape}",
                instruction="Instruction",
                **audit,
            )
            project_point = ProjectInspectionPoint(
                project_inspection_item_id=project_item.id,
                sequence=sequence,
                title=f"Project point {shape}",
                instruction="Instruction",
                **audit,
            )
            session.add_all([template_point, project_point])
            session.flush()
            # (min_count, minutes after base, keep this row?)
            rows = {
                "largest": ((1, 0, False), (5, 1, True), (3, 2, False)),
                "tie": ((2, 3, False), (2, 1, True)),
                "single": ((4, 0, True),),
            }[shape]
            for min_count, minutes, keep in rows:
                row_id = uuid4()
                stamp = base + timedelta(minutes=minutes)
                session.add_all(
                    [
                        TemplateEvidenceRequirement(
                            id=row_id,
                            inspection_point_id=template_point.id,
                            min_count=min_count,
                            created_at=stamp,
                            **audit,
                        ),
                        ProjectEvidenceRequirement(
                            id=row_id,
                            inspection_point_id=project_point.id,
                            project_inspection_item_id=project_item.id,
                            min_count=min_count,
                            created_at=stamp,
                            **audit,
                        ),
                    ]
                )
                if keep:
                    kept[f"{shape}:{sequence}"] = row_id
                else:
                    dropped.append(row_id)
        session.commit()

    def remaining(table: str) -> set[UUID]:
        with engine.connect() as connection:
            return {
                row[0] if isinstance(row[0], UUID) else UUID(str(row[0]))
                for row in connection.execute(text(f"SELECT id FROM {table}"))
            }

    def counts() -> dict[str, int]:
        with engine.connect() as connection:
            return {
                table: connection.execute(
                    text(f"SELECT COUNT(*) FROM {table}")
                ).scalar_one()
                for table in (
                    "template_inspection_points",
                    "project_inspection_points",
                    "project_inspection_items",
                )
            }

    parents_before = counts()
    assert len(remaining("template_evidence_requirements")) == 6

    command.upgrade(cfg, migration_revision)
    for table in indexes:
        assert remaining(table) == set(kept.values())
        assert not set(dropped) & remaining(table)
    assert unique_indexes(engine) == dict.fromkeys(indexes, True)
    assert counts() == parents_before
    with engine.connect() as connection:
        mins = sorted(
            connection.execute(
                text("SELECT min_count FROM project_evidence_requirements")
            ).scalars()
        )
    assert mins == [2, 4, 5]

    command.downgrade(cfg, previous_revision)
    assert unique_indexes(engine) == dict.fromkeys(indexes, False)
    assert counts() == parents_before
    for table in indexes:
        assert remaining(table) == set(kept.values())

    command.upgrade(cfg, "head")
    assert unique_indexes(engine) == dict.fromkeys(indexes, True)
    for table in indexes:
        assert remaining(table) == set(kept.values())
    engine.dispose()


_PRE_EXISTING_LOGGER_NAME = "tests.db.test_migrations.pre_existing_logger"


@pytest.fixture
def upgraded_db_with_pre_existing_logger(db_url) -> logging.Logger:
    """Create a logger *before* migrating (mirrors the application:
    ``app.api.errors``'s module-level logger already exists by the
    time a migration ever runs), then migrate. Runs during fixture
    setup, like ``tests/auth/conftest.py``'s ``migrated_url`` --
    not inside the test body -- so the assertions below see the
    same pytest log-capture setup real callers see.
    """
    logger = logging.getLogger(_PRE_EXISTING_LOGGER_NAME)
    command.upgrade(_alembic_config(), "head")
    return logger


def test_upgrade_head_keeps_a_pre_existing_logger_enabled(
    upgraded_db_with_pre_existing_logger, caplog
):
    """Issue #185: ``fileConfig``'s default ``disable_existing_loggers``
    is ``True``, which -- when a migration runs in the same process
    as code that already created its own logger (the application, or
    an earlier fixture/test) -- disables that logger for the rest of
    the process. ``env.py`` must pass
    ``disable_existing_loggers=False`` so a logger created before
    ``command.upgrade`` runs still emits records afterwards.
    """
    logger = upgraded_db_with_pre_existing_logger

    assert logger.disabled is False
    with caplog.at_level(logging.INFO, logger=_PRE_EXISTING_LOGGER_NAME):
        logger.info("still alive after migration")

    assert any(
        record.name == _PRE_EXISTING_LOGGER_NAME
        and record.getMessage() == "still alive after migration"
        for record in caplog.records
    )


def test_upgrade_head_works_from_a_non_backend_working_directory(
    db_url, tmp_path, monkeypatch
):
    """env.py must not depend on the process's current working
    directory to import ``app`` or to locate the database: this
    test runs with ``tmp_path`` (not ``backend/``) as cwd, relying
    only on ``alembic.ini``'s own ``%(here)s``-based
    ``prepend_sys_path`` and on passing an absolute ``alembic.ini``
    path to ``Config``.
    """
    monkeypatch.chdir(tmp_path)
    cfg = _alembic_config()

    command.upgrade(cfg, "head")

    expected_head = ScriptDirectory.from_config(cfg).get_current_head()
    assert _stamped_version(db_url) == expected_head
