"""add audit_logs table

Revision ID: 4c38ff477939
Revises: 710e91fda9cd
Create Date: 2026-09-27 10:59:41.144718

``AuditLog`` (ALG-R01~ALG-R04): a UUID primary key, ``created_at``/
``created_by`` (no ``updated_at``/``updated_by`` -- ALG-R02, see
``app/models/audit_log.py``), ``event_type``/``entity_type``,
``entity_id`` (deliberately not a foreign key -- ALG-R03, so a
deleted entity's history survives it) and nullable ``before``/
``after`` JSON columns. The only foreign key is ``created_by`` into
``users.id``. The database-level "append-only" guard itself
(ALG-R04) is application code, not a database constraint (see that
module's docstring for why); this migration only creates the table
shape.
"""

from collections.abc import Sequence

# sa and op are unused in an empty migration (e.g. the baseline);
# the template keeps them so every migration starts with both.
import sqlalchemy as sa  # noqa: F401

from alembic import op  # noqa: F401

# Use only SQLAlchemy built-in types (e.g. sa.DateTime(timezone=True))
# and never import from app: a migration must replay unchanged
# whatever the app code later becomes (#139).

# revision identifiers, used by Alembic.
revision: str = "4c38ff477939"
down_revision: str | Sequence[str] | None = "710e91fda9cd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("entity_type", sa.String(), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("before", sa.JSON(), nullable=True),
        sa.Column("after", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_audit_logs_created_by_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
