"""add user business fields

Revision ID: 600b0736442e
Revises: 88da78b69aa7
Create Date: 2026-09-26 19:55:30.923481

``User`` business fields (DOM-R01, DOM-R02, DOM-R03, DOM-R05,
DOM-R08, DOM-R28, DOM-R31, DOM-Q7's issue #127 decision): the
basic, contact/supplementary, system and reserved external-identity
columns ``app/models/user.py`` defines, on top of the common
structure ``78a4ba191ab5`` already created.

Uses ``op.batch_alter_table`` like ``22bfdd8a72a4`` before it:
SQLite has no native ``ALTER TABLE ... ADD COLUMN ... NOT NULL``
(without a default) and no way to add a foreign key or CHECK
constraint to an existing table at all, so batch mode rebuilds
``users`` by copying its rows into a new table and dropping the old
one. ``users`` has no data of its own yet at this point in the
chain, so the rebuild needs no data migration.

``PRAGMA foreign_keys`` is toggled off for the duration of the
rebuild, on SQLite only, the same way ``22bfdd8a72a4`` did for
``projects`` referencing ``users`` -- except this time *four* other
tables (``companies``, ``projects``, ``user_passwords``,
``auth_sessions``) reference ``users.id``, and ``users`` itself
carries a foreign key back into ``companies`` (``company_id``,
DEFERRABLE INITIALLY DEFERRED -- see the model's docstring and
plan.md's "風險" section for why: ``User``/``Company`` reference
each other, and only one side can defer). Verified empirically
(``tests/db/test_user_fields.py``'s round-trip test) that toggling
the pragma off for the rebuild is sufficient on SQLite even with
this many referencing tables and the self-referential
``created_by``/``updated_by`` columns ``users`` already had:
batch mode's rename-based rebuild is transparent to every
referencing table's foreign key definition once the pragma no
longer enforces them mid-rebuild, and turning it back on afterwards
re-enables enforcement against the now-complete final schema.
``PRAGMA foreign_keys`` is a connection-level, non-transactional
setting on SQLite (unlike a table's DDL), so if this migration
fails partway through, the pragma may be left off for the rest of
the connection's lifetime -- the same caveat ``22bfdd8a72a4``
already carries, not new here.

``email``'s case-insensitive uniqueness (DOM-R02) is a functional
unique index on ``lower(email)`` (``ix_users_email_lower``), not a
plain column-level constraint -- see ``app/models/user.py``'s
docstring. This is created with a plain ``op.create_index`` after
the batch block, not inside it: it needs no table rebuild on
either backend (a expression index is just its own independent
database object), and ``op.batch_alter_table``'s reflection-based
recreate cannot represent an expression index at all -- SQLAlchemy
cannot reflect one back off SQLite (confirmed by the
``UserWarning: autogenerate skipping metadata-specified
expression-based index 'ix_users_email_lower'`` this revision's
``alembic revision --autogenerate`` run emitted). Because SQLite can
never reflect this index, ``alembic check`` can never see it as
drift either way on that backend -- it is silently invisible to the
comparison in both directions, so creating it here by hand (with no
autogenerate-managed counterpart) does not itself cause drift; the
test suite instead asserts the index is enforced by writing through
it directly (``tests/db/test_user_fields.py``).

The ``auth_source`` value-list CHECK and the "external fields
required when ``auth_source = external``" CHECK are not
autogenerated either (Alembic's autogenerate does not diff CHECK
constraints by default) and are added by hand inside the batch
block, alongside the columns and the ``external_source``/
``external_id`` unique constraint autogenerate did detect.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from app.db.base import UTCDateTime

# revision identifiers, used by Alembic.
revision: str = "600b0736442e"
down_revision: str | Sequence[str] | None = "88da78b69aa7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    is_sqlite = op.get_bind().dialect.name == "sqlite"
    if is_sqlite:
        op.execute("PRAGMA foreign_keys=OFF")
    try:
        with op.batch_alter_table("users") as batch_op:
            batch_op.add_column(
                sa.Column("company_id", sa.Uuid(), nullable=False)
            )
            batch_op.add_column(
                sa.Column("department", sa.String(length=64), nullable=False)
            )
            batch_op.add_column(
                sa.Column("location", sa.String(length=64), nullable=False)
            )
            batch_op.add_column(
                sa.Column("name_en", sa.String(length=128), nullable=False)
            )
            batch_op.add_column(
                sa.Column("name_zh", sa.String(length=64), nullable=False)
            )
            batch_op.add_column(
                sa.Column("email", sa.String(length=254), nullable=False)
            )
            batch_op.add_column(
                sa.Column(
                    "is_active",
                    sa.Boolean(),
                    nullable=False,
                    server_default=sa.true(),
                )
            )
            batch_op.add_column(
                sa.Column("extension_1", sa.String(length=64), nullable=True)
            )
            batch_op.add_column(
                sa.Column("extension_2", sa.String(length=64), nullable=True)
            )
            batch_op.add_column(
                sa.Column("mobile", sa.String(length=64), nullable=True)
            )
            batch_op.add_column(
                sa.Column("line_id", sa.String(length=64), nullable=True)
            )
            batch_op.add_column(
                sa.Column("wechat_id", sa.String(length=64), nullable=True)
            )
            batch_op.add_column(
                sa.Column(
                    "responsibilities", sa.String(length=2000), nullable=True
                )
            )
            batch_op.add_column(
                sa.Column(
                    "is_admin",
                    sa.Boolean(),
                    nullable=False,
                    server_default=sa.false(),
                )
            )
            batch_op.add_column(
                sa.Column(
                    "is_system",
                    sa.Boolean(),
                    nullable=False,
                    server_default=sa.false(),
                )
            )
            batch_op.add_column(
                sa.Column(
                    "auth_source",
                    sa.String(),
                    nullable=False,
                    server_default="local",
                )
            )
            batch_op.add_column(
                sa.Column("external_source", sa.String(), nullable=True)
            )
            batch_op.add_column(
                sa.Column("external_id", sa.String(), nullable=True)
            )
            batch_op.add_column(
                sa.Column(
                    "external_synced_at",
                    UTCDateTime(timezone=True),
                    nullable=True,
                )
            )
            batch_op.create_foreign_key(
                batch_op.f("fk_users_company_id_companies"),
                "companies",
                ["company_id"],
                ["id"],
                deferrable=True,
                initially="DEFERRED",
            )
            batch_op.create_unique_constraint(
                batch_op.f("uq_users_external_source"),
                ["external_source", "external_id"],
            )
            batch_op.create_check_constraint(
                batch_op.f("ck_users_auth_source"),
                "auth_source IN ('local', 'external')",
            )
            batch_op.create_check_constraint(
                batch_op.f("ck_users_external_fields_required"),
                "auth_source <> 'external' OR "
                "(external_source IS NOT NULL AND external_id IS NOT NULL)",
            )
    finally:
        if is_sqlite:
            op.execute("PRAGMA foreign_keys=ON")

    op.create_index(
        "ix_users_email_lower",
        "users",
        [sa.text("lower(email)")],
        unique=True,
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("ix_users_email_lower", table_name="users")

    is_sqlite = op.get_bind().dialect.name == "sqlite"
    if is_sqlite:
        op.execute("PRAGMA foreign_keys=OFF")
    try:
        with op.batch_alter_table("users") as batch_op:
            batch_op.drop_constraint(
                batch_op.f("ck_users_external_fields_required"),
                type_="check",
            )
            batch_op.drop_constraint(
                batch_op.f("ck_users_auth_source"), type_="check"
            )
            batch_op.drop_constraint(
                batch_op.f("uq_users_external_source"), type_="unique"
            )
            batch_op.drop_constraint(
                batch_op.f("fk_users_company_id_companies"),
                type_="foreignkey",
            )
            batch_op.drop_column("external_synced_at")
            batch_op.drop_column("external_id")
            batch_op.drop_column("external_source")
            batch_op.drop_column("auth_source")
            batch_op.drop_column("is_system")
            batch_op.drop_column("is_admin")
            batch_op.drop_column("responsibilities")
            batch_op.drop_column("wechat_id")
            batch_op.drop_column("line_id")
            batch_op.drop_column("mobile")
            batch_op.drop_column("extension_2")
            batch_op.drop_column("extension_1")
            batch_op.drop_column("is_active")
            batch_op.drop_column("email")
            batch_op.drop_column("name_zh")
            batch_op.drop_column("name_en")
            batch_op.drop_column("location")
            batch_op.drop_column("department")
            batch_op.drop_column("company_id")
    finally:
        if is_sqlite:
            op.execute("PRAGMA foreign_keys=ON")
