"""add inspection planning schema

Revision ID: 6d2e4f8a91b0
Revises: a8356e4c12b0
Create Date: 2026-10-04 15:14:51.141219

"""

from collections.abc import Sequence

# sa and op are unused in an empty migration (e.g. the baseline);
# the template keeps them so every migration starts with both.
import sqlalchemy as sa  # noqa: F401

from alembic import op  # noqa: F401

# Use only SQLAlchemy built-in types (e.g. sa.DateTime(timezone=True))
# and never import from app: a migration must replay unchanged
# whatever the app code later becomes (#139).

# revision identifiers, used by Alembic.
revision: str = "6d2e4f8a91b0"
down_revision: str | Sequence[str] | None = "a8356e4c12b0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inspection_plans",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column(
            "status",
            sa.String(length=16),
            server_default="DRAFT",
            nullable=False,
        ),
        sa.Column(
            "is_archived", sa.Boolean(), server_default="0", nullable=False
        ),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')",
            name=op.f("ck_inspection_plans_inspection_plan_status_valid"),
        ),
        sa.CheckConstraint(
            "length(trim(name)) BETWEEN 1 AND 128",
            name=op.f("ck_inspection_plans_inspection_plan_name_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_inspection_plans_created_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_inspection_plans_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_inspection_plans_updated_by_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inspection_plans")),
        sa.UniqueConstraint(
            "id", "project_id", name=op.f("uq_inspection_plans_id")
        ),
    )
    op.create_table(
        "project_zones",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("name_key", sa.String(length=512), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "name <> ''",
            name=op.f("ck_project_zones_project_zone_name_nonempty"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_project_zones_created_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_zones_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_project_zones_updated_by_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_zones")),
        sa.UniqueConstraint(
            "project_id", "id", name="uq_project_zones_project_id_id"
        ),
        sa.UniqueConstraint(
            "project_id", "name_key", name="uq_project_zones_project_name"
        ),
    )
    op.create_table(
        "inspection_tasks",
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("zone_id", sa.Uuid(), nullable=True),
        sa.Column("location_text", sa.String(length=256), nullable=True),
        sa.Column(
            "status",
            sa.String(length=16),
            server_default="DRAFT",
            nullable=False,
        ),
        sa.Column(
            "cancelled_from_status", sa.String(length=16), nullable=True
        ),
        sa.Column("cancellation_reason", sa.String(), nullable=True),
        sa.Column("assignee_id", sa.Uuid(), nullable=True),
        sa.Column("started_by", sa.Uuid(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_by", sa.Uuid(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(status = 'CANCELLED' AND cancelled_from_status IS NOT NULL "
            "AND cancellation_reason IS NOT NULL "
            "AND length(trim(cancellation_reason)) > 0) OR "
            "(status != 'CANCELLED' AND cancelled_from_status IS NULL "
            "AND cancellation_reason IS NULL)",
            name=op.f(
                "ck_inspection_tasks_inspection_task_cancellation_consistent"
            ),
        ),
        sa.CheckConstraint(
            "cancelled_from_status IS NULL OR cancelled_from_status "
            "IN ('PENDING', 'IN_PROGRESS')",
            name=op.f(
                "ck_inspection_tasks_inspection_task_cancelled_from_valid"
            ),
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'PENDING', 'IN_PROGRESS', "
            "'COMPLETED', 'CANCELLED')",
            name=op.f("ck_inspection_tasks_inspection_task_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["users.id"],
            name=op.f("fk_inspection_tasks_assignee_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["completed_by"],
            ["users.id"],
            name=op.f("fk_inspection_tasks_completed_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_inspection_tasks_created_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["plan_id", "project_id"],
            ["inspection_plans.id", "inspection_plans.project_id"],
            name=op.f("fk_inspection_tasks_plan_id_inspection_plans"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "zone_id"],
            ["project_zones.project_id", "project_zones.id"],
            name=op.f("fk_inspection_tasks_project_id_project_zones"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["started_by"],
            ["users.id"],
            name=op.f("fk_inspection_tasks_started_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_inspection_tasks_updated_by_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inspection_tasks")),
        sa.UniqueConstraint(
            "id", "project_id", name=op.f("uq_inspection_tasks_id")
        ),
    )
    op.create_table(
        "project_inspection_item_changes",
        sa.Column("project_inspection_item_id", sa.Uuid(), nullable=False),
        sa.Column("before_revision", sa.Integer(), nullable=False),
        sa.Column("after_revision", sa.Integer(), nullable=False),
        sa.Column("reinspection_required", sa.Boolean(), nullable=True),
        sa.Column("before_data", sa.JSON(), nullable=False),
        sa.Column("after_data", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "after_revision > before_revision",
            name=op.f(
                "ck_project_inspection_item_changes_project_item_change_revision_increases"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_project_inspection_item_changes_created_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["project_inspection_item_id"],
            ["project_inspection_items.id"],
            name=op.f(
                "fk_project_inspection_item_changes_project_inspection_item_id_project_inspection_items"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_project_inspection_item_changes_updated_by_users"),
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_project_inspection_item_changes")
        ),
        sa.UniqueConstraint(
            "project_inspection_item_id",
            "after_revision",
            name=op.f(
                "uq_project_inspection_item_changes_project_inspection_item_id"
            ),
        ),
    )
    op.add_column(
        "project_inspection_items",
        sa.Column(
            "standard_revision",
            sa.Integer(),
            server_default="1",
            nullable=False,
        ),
    )
    op.create_index(
        "uq_project_inspection_items_id_project_id",
        "project_inspection_items",
        ["id", "project_id"],
        unique=True,
    )

    op.create_table(
        "task_inspection_items",
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("project_inspection_item_id", sa.Uuid(), nullable=False),
        sa.Column(
            "item_status",
            sa.String(length=16),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column(
            "needs_reinspection",
            sa.Boolean(),
            server_default="0",
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "item_status IN ('PENDING', 'COMPLETED')",
            name=op.f(
                "ck_task_inspection_items_task_inspection_item_status_valid"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_task_inspection_items_created_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["project_inspection_item_id", "project_id"],
            [
                "project_inspection_items.id",
                "project_inspection_items.project_id",
            ],
            name=op.f(
                "fk_task_inspection_items_project_inspection_item_id_project_inspection_items"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_id", "project_id"],
            ["inspection_tasks.id", "inspection_tasks.project_id"],
            name=op.f("fk_task_inspection_items_task_id_inspection_tasks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_task_inspection_items_updated_by_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_inspection_items")),
        sa.UniqueConstraint(
            "task_id",
            "project_inspection_item_id",
            name=op.f("uq_task_inspection_items_task_id"),
        ),
    )
    op.create_table(
        "task_requirement_snapshots",
        sa.Column("task_inspection_item_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("source_standard_revision", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("instruction", sa.String(), nullable=False),
        sa.Column("source_template_name", sa.String(), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("superseded_reason", sa.String(length=32), nullable=True),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "superseded_reason IS NULL OR superseded_reason IN "
            "('STANDARD_CHANGED', 'TEXT_CORRECTED')",
            name=op.f(
                "ck_task_requirement_snapshots_task_snapshot_superseded_reason_valid"
            ),
        ),
        sa.CheckConstraint(
            "(is_current AND superseded_reason IS NULL "
            "AND superseded_at IS NULL) OR "
            "(NOT is_current AND superseded_reason IS NOT NULL "
            "AND superseded_at IS NOT NULL)",
            name=op.f(
                "ck_task_requirement_snapshots_task_snapshot_current_consistent"
            ),
        ),
        sa.CheckConstraint(
            "revision >= 1",
            name=op.f(
                "ck_task_requirement_snapshots_task_snapshot_revision_positive"
            ),
        ),
        sa.CheckConstraint(
            "source_standard_revision >= 1",
            name=op.f(
                "ck_task_requirement_snapshots_task_snapshot_source_revision_positive"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_task_requirement_snapshots_created_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["task_inspection_item_id"],
            ["task_inspection_items.id"],
            name=op.f(
                "fk_task_requirement_snapshots_task_inspection_item_id_task_inspection_items"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_task_requirement_snapshots_updated_by_users"),
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_task_requirement_snapshots")
        ),
        sa.UniqueConstraint(
            "task_inspection_item_id",
            "revision",
            name=op.f("uq_task_requirement_snapshots_task_inspection_item_id"),
        ),
    )
    with op.batch_alter_table(
        "task_requirement_snapshots", schema=None
    ) as batch_op:
        batch_op.create_index(
            "uq_task_requirement_snapshots_current",
            ["task_inspection_item_id"],
            unique=True,
            sqlite_where=sa.text("is_current = 1"),
            postgresql_where=sa.text("is_current = true"),
        )

    op.create_table(
        "task_snapshot_points",
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("source_point_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("instruction", sa.String(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_task_snapshot_points_created_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["task_requirement_snapshots.id"],
            name=op.f(
                "fk_task_snapshot_points_snapshot_id_task_requirement_snapshots"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_task_snapshot_points_updated_by_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_snapshot_points")),
        sa.UniqueConstraint(
            "snapshot_id",
            "sequence",
            name="uq_snapshot_point_sequence",
        ),
        sa.UniqueConstraint(
            "snapshot_id",
            "source_point_id",
            name="uq_snapshot_point_source",
        ),
    )
    op.create_table(
        "task_snapshot_evidence_requirements",
        sa.Column("point_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_type", sa.String(length=16), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("min_count", sa.Integer(), nullable=False),
        sa.Column("max_count", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "evidence_type = 'photo'",
            name=op.f(
                "ck_task_snapshot_evidence_requirements_task_snapshot_evidence_photo"
            ),
        ),
        sa.CheckConstraint(
            "max_count IS NULL",
            name=op.f(
                "ck_task_snapshot_evidence_requirements_task_snapshot_evidence_unbounded"
            ),
        ),
        sa.CheckConstraint(
            "min_count >= 1",
            name=op.f(
                "ck_task_snapshot_evidence_requirements_task_snapshot_evidence_min_positive"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f(
                "fk_task_snapshot_evidence_requirements_created_by_users"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["point_id"],
            ["task_snapshot_points.id"],
            name=op.f(
                "fk_task_snapshot_evidence_requirements_point_id_task_snapshot_points"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f(
                "fk_task_snapshot_evidence_requirements_updated_by_users"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_task_snapshot_evidence_requirements")
        ),
        sa.UniqueConstraint(
            "point_id",
            "evidence_type",
            name=op.f("uq_task_snapshot_evidence_requirements_point_id"),
        ),
    )
    op.create_table(
        "task_snapshot_measurement_fields",
        sa.Column("point_id", sa.Uuid(), nullable=False),
        sa.Column("source_field_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("field_type", sa.String(length=16), nullable=False),
        sa.Column("unit", sa.String(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "field_type IN ('text', 'number')",
            name=op.f(
                "ck_task_snapshot_measurement_fields_task_snapshot_field_type_valid"
            ),
        ),
        sa.CheckConstraint(
            "field_type != 'number' OR unit IS NOT NULL",
            name=op.f(
                "ck_task_snapshot_measurement_fields_task_snapshot_number_field_requires_unit"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_task_snapshot_measurement_fields_created_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["point_id"],
            ["task_snapshot_points.id"],
            name=op.f(
                "fk_task_snapshot_measurement_fields_point_id_task_snapshot_points"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_task_snapshot_measurement_fields_updated_by_users"),
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_task_snapshot_measurement_fields")
        ),
        sa.UniqueConstraint(
            "point_id",
            "source_field_id",
            name=op.f("uq_task_snapshot_measurement_fields_point_id"),
        ),
        sa.UniqueConstraint(
            "point_id",
            "source_field_id",
            "field_type",
            "unit",
            name="uq_snapshot_field_point_source_type_unit",
        ),
    )
    op.create_table(
        "task_snapshot_numeric_standards",
        sa.Column("point_id", sa.Uuid(), nullable=False),
        sa.Column("value", sa.String(), nullable=True),
        sa.Column("condition", sa.String(), nullable=False),
        sa.Column("unit", sa.String(), nullable=False),
        sa.Column("tolerance", sa.String(), nullable=True),
        sa.Column("range_form", sa.String(length=16), nullable=True),
        sa.Column("lower_bound", sa.String(), nullable=True),
        sa.Column("upper_bound", sa.String(), nullable=True),
        sa.Column("source_measurement_field_id", sa.Uuid(), nullable=False),
        sa.Column(
            "measurement_field_type",
            sa.String(length=16),
            server_default="number",
            nullable=False,
        ),
        sa.Column("measurement_field_unit", sa.String(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "condition IN ('<=', '>=', '=', 'range')",
            name=op.f(
                "ck_task_snapshot_numeric_standards_task_snapshot_numeric_condition_valid"
            ),
        ),
        sa.CheckConstraint(
            "measurement_field_type = 'number'",
            name=op.f(
                "ck_task_snapshot_numeric_standards_task_snapshot_numeric_requires_number_field"
            ),
        ),
        sa.CheckConstraint(
            "unit = measurement_field_unit",
            name=op.f(
                "ck_task_snapshot_numeric_standards_task_snapshot_numeric_unit_matches_field"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_task_snapshot_numeric_standards_created_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["point_id"],
            ["task_snapshot_points.id"],
            name=op.f(
                "fk_task_snapshot_numeric_standards_point_id_task_snapshot_points"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            [
                "point_id",
                "source_measurement_field_id",
                "measurement_field_type",
                "measurement_field_unit",
            ],
            [
                "task_snapshot_measurement_fields.point_id",
                "task_snapshot_measurement_fields.source_field_id",
                "task_snapshot_measurement_fields.field_type",
                "task_snapshot_measurement_fields.unit",
            ],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_task_snapshot_numeric_standards_updated_by_users"),
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_task_snapshot_numeric_standards")
        ),
        sa.UniqueConstraint(
            "point_id",
            name=op.f("uq_task_snapshot_numeric_standards_point_id"),
        ),
    )
    op.create_table(
        "task_snapshot_text_standards",
        sa.Column("point_id", sa.Uuid(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_task_snapshot_text_standards_created_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["point_id"],
            ["task_snapshot_points.id"],
            name=op.f(
                "fk_task_snapshot_text_standards_point_id_task_snapshot_points"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_task_snapshot_text_standards_updated_by_users"),
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_task_snapshot_text_standards")
        ),
        sa.UniqueConstraint(
            "point_id", name=op.f("uq_task_snapshot_text_standards_point_id")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task_snapshot_text_standards")
    op.drop_table("task_snapshot_numeric_standards")
    op.drop_table("task_snapshot_measurement_fields")
    op.drop_table("task_snapshot_evidence_requirements")
    op.drop_table("task_snapshot_points")
    with op.batch_alter_table(
        "task_requirement_snapshots", schema=None
    ) as batch_op:
        batch_op.drop_index(
            "uq_task_requirement_snapshots_current",
            sqlite_where=sa.text("is_current = 1"),
            postgresql_where=sa.text("is_current = true"),
        )

    op.drop_table("task_requirement_snapshots")
    op.drop_table("task_inspection_items")
    op.drop_table("project_inspection_item_changes")
    op.drop_table("inspection_tasks")
    op.drop_table("project_zones")
    op.drop_table("inspection_plans")
    op.drop_index(
        "uq_project_inspection_items_id_project_id",
        table_name="project_inspection_items",
    )
    op.drop_column("project_inspection_items", "standard_revision")
    # ### end Alembic commands ###
