"""module permission tables

Revision ID: 6eaaafbe0ef2
Revises: d5a2c8e7b194
Create Date: 2026-10-10 12:35:27.975943

"""

from collections.abc import Sequence

# sa and op are unused in an empty migration (e.g. the baseline);
# the template keeps them so every migration starts with both.
import sqlalchemy as sa  # noqa: F401

from alembic import op  # noqa: F401

# Use only SQLAlchemy built-in types (e.g. sa.DateTime(timezone=True))
# and never import from app: a migration must replay unchanged
# whatever the app code later becomes (#139).

# revision identifiers, used by Alembic.
revision: str = "6eaaafbe0ef2"
down_revision: str | Sequence[str] | None = "d5a2c8e7b194"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _sqlite_foreign_keys(enabled: bool) -> None:
    if op.get_bind().dialect.name == "sqlite":
        # db-dependency: sqlite; SQLite cannot rebuild referenced tables
        # with foreign-key enforcement enabled.
        op.execute("PRAGMA foreign_keys=" + ("ON" if enabled else "OFF"))


def upgrade() -> None:
    _sqlite_foreign_keys(False)
    try:
        _upgrade()
    finally:
        _sqlite_foreign_keys(True)


def _upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permission_bundles",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_permission_bundles_created_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_permission_bundles_updated_by_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permission_bundles")),
    )
    op.create_table(
        "user_module_delegations",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("module", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "module IN ('project', 'inspection', 'template')",
            name=op.f("ck_user_module_delegations_module"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_module_delegations_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_module_delegations")),
        sa.UniqueConstraint(
            "user_id",
            "module",
            name=op.f("uq_user_module_delegations_user_id"),
        ),
    )
    op.create_table(
        "user_module_permissions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("permission_code", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "source IN ('manual', 'implied', 'bundle', 'backfill')",
            name=op.f("ck_user_module_permissions_source"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_module_permissions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_module_permissions")),
        sa.UniqueConstraint(
            "user_id",
            "permission_code",
            name=op.f("uq_user_module_permissions_user_id"),
        ),
    )
    op.create_table(
        "creator_role_settings",
        sa.Column(
            "setting_key",
            sa.String(length=32),
            server_default="creator_role",
            nullable=False,
        ),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "setting_key = 'creator_role'",
            name=op.f("ck_creator_role_settings_setting_key"),
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_creator_role_settings_role_id_roles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_creator_role_settings")),
        sa.UniqueConstraint(
            "setting_key", name=op.f("uq_creator_role_settings_setting_key")
        ),
    )
    op.create_table(
        "permission_bundle_permissions",
        sa.Column("bundle_id", sa.Uuid(), nullable=False),
        sa.Column("permission_code", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["bundle_id"],
            ["permission_bundles.id"],
            name=op.f(
                "fk_permission_bundle_permissions_bundle_id_permission_bundles"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_permission_bundle_permissions")
        ),
        sa.UniqueConstraint(
            "bundle_id",
            "permission_code",
            name=op.f("uq_permission_bundle_permissions_bundle_id"),
        ),
    )
    op.create_index(
        "ix_permission_bundles_name_lower",
        "permission_bundles",
        [sa.text("lower(name)")],
        unique=True,
    )
    # SQLite batch mode rebuilds the table and cannot reflect functional
    # indexes. Drop and recreate the index around the rebuild explicitly.
    op.drop_index("ix_roles_name_lower", table_name="roles")
    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_assignable",
                sa.Boolean(),
                server_default=sa.text("0"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "is_external_allowed",
                sa.Boolean(),
                server_default=sa.text("0"),
                nullable=False,
            )
        )
    op.create_index(
        "ix_roles_name_lower",
        "roles",
        [sa.text("lower(name)")],
        unique=True,
    )

    # The user rebuild has the same SQLite reflection limitation for its
    # case-insensitive email index.
    op.drop_index("ix_users_email_lower", table_name="users")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_external_collaborator", sa.Boolean())
        )
        batch_op.add_column(
            sa.Column("account_expires_on", sa.Date(), nullable=True)
        )
        batch_op.create_check_constraint(
            op.f("ck_users_external_expiry_only"),
            "is_external_collaborator OR account_expires_on IS NULL",
        )

    op.execute(
        "UPDATE users SET is_external_collaborator = 0 "
        "WHERE is_external_collaborator IS NULL"
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "is_external_collaborator",
            existing_type=sa.Boolean(),
            nullable=False,
        )
    op.create_index(
        "ix_users_email_lower",
        "users",
        [sa.text("lower(email)")],
        unique=True,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    _sqlite_foreign_keys(False)
    try:
        _downgrade()
    finally:
        _sqlite_foreign_keys(True)


def _downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_users_email_lower", table_name="users")
    op.drop_index("ix_roles_name_lower", table_name="roles")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(
            op.f("ck_users_external_expiry_only"), type_="check"
        )
        batch_op.drop_column("account_expires_on")
        batch_op.drop_column("is_external_collaborator")

    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.drop_column("is_external_allowed")
        batch_op.drop_column("is_assignable")

    # Restore the pre-revision functional indexes after SQLite table
    # rebuilds; older revisions still expect these indexes to exist.
    op.create_index(
        "ix_users_email_lower",
        "users",
        [sa.text("lower(email)")],
        unique=True,
    )
    op.create_index(
        "ix_roles_name_lower",
        "roles",
        [sa.text("lower(name)")],
        unique=True,
    )

    op.drop_table("permission_bundle_permissions")
    op.drop_table("creator_role_settings")
    op.drop_table("user_module_permissions")
    op.drop_table("user_module_delegations")
    op.drop_table("permission_bundles")
    # ### end Alembic commands ###
