"""add roles and project members tables

Revision ID: 710e91fda9cd
Revises: 0fb7eb5f0dcd
Create Date: 2026-09-27 09:45:44.485391

``Role``/``RolePermission`` (DOM-R15, DOM-R19, DOM-R20, DOM-R21,
DOM-R30, DOM-R34) and ``ProjectMember``/``ProjectMemberRole``
(DOM-R15, DOM-R25): see ``app/models/role.py`` and
``app/models/project_member.py`` for why the two child tables
(``role_permissions``, ``project_member_roles``) get only a UUID
primary key and timestamps, not the full ``created_by``/
``updated_by`` audit columns their parent tables have, and why their
foreign keys back to ``roles``/``project_members`` are
``ON DELETE CASCADE`` (DOM-R21, issue #131's DOM-Q5 decision) rather
than managed by the ORM.

``name``'s case-insensitive uniqueness (DOM-R34) is a functional
unique index on ``lower(name)`` (``ix_roles_name_lower``), the same
pattern ``600b0736442e`` used for ``User.email``: created with a
plain ``op.create_index`` (a brand new table needs no
``op.batch_alter_table`` rebuild here), and not autogenerated --
SQLAlchemy cannot reflect an expression index back off SQLite
(confirmed by the same ``UserWarning: autogenerate skipping
metadata-specified expression-based index 'ix_roles_name_lower'``
this revision's own ``alembic revision --autogenerate`` run emitted,
alongside the pre-existing one for ``ix_users_email_lower``).
"""

from collections.abc import Sequence

# sa and op are unused in an empty migration (e.g. the baseline);
# the template keeps them so every migration starts with both.
import sqlalchemy as sa  # noqa: F401

from alembic import op  # noqa: F401

# Use only SQLAlchemy built-in types (e.g. sa.DateTime(timezone=True))
# and never import from app: a migration must replay unchanged
# whatever the app code later becomes (#139).

# revision identifiers, used by Alembic.
revision: str = "710e91fda9cd"
down_revision: str | Sequence[str] | None = "0fb7eb5f0dcd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roles",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_roles_created_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_roles_updated_by_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
    )
    op.create_index(
        "ix_roles_name_lower",
        "roles",
        [sa.text("lower(name)")],
        unique=True,
    )
    op.create_table(
        "project_members",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_project_members_created_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_members_project_id_projects"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_project_members_updated_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_project_members_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_members")),
        sa.UniqueConstraint(
            "project_id", "user_id", name=op.f("uq_project_members_project_id")
        ),
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_role_permissions_role_id_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role_permissions")),
        sa.UniqueConstraint(
            "role_id", "code", name=op.f("uq_role_permissions_role_id")
        ),
    )
    op.create_table(
        "project_member_roles",
        sa.Column("project_member_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_member_id"],
            ["project_members.id"],
            name=op.f(
                "fk_project_member_roles_project_member_id_project_members"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_project_member_roles_role_id_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_member_roles")),
        sa.UniqueConstraint(
            "project_member_id",
            "role_id",
            name=op.f("uq_project_member_roles_project_member_id"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_member_roles")
    op.drop_table("role_permissions")
    op.drop_table("project_members")
    op.drop_index("ix_roles_name_lower", table_name="roles")
    op.drop_table("roles")
    # ### end Alembic commands ###
